#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 12 15:45:32 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ad5e223ac44b468eacd84b828cacf10a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot fulladder4bittestbench_behav xil_defaultlib.fulladder4bittestbench xil_defaultlib.glbl -log elaborate.log"
xelab -wto ad5e223ac44b468eacd84b828cacf10a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot fulladder4bittestbench_behav xil_defaultlib.fulladder4bittestbench xil_defaultlib.glbl -log elaborate.log

